### ISSUE TITLE
pack column for Tableviewer

### ISSUE THREAD

**Issue by demetr88** [eclipse-rap/org.eclipse.rap#120] opened 2023-03-29 23:35 UTC
If I set getTable().getColumn(index).pack() for a field with bold, the value does not fit in the cell and has '...' at the end of the value.
If I don't use bold, the value fits in the cell

**Comment by ifurnadjiev** [comment] 2024-08-14 14:36
Duplicate of https://github.com/eclipse-rap/org.eclipse.rap/issues/197

**Closed by ifurnadjiev** 2024-08-14 14:36 UTC
